### ISSUE TITLE
Improve module installation error reporting and test failure handling

### ISSUE THREAD

**Issue by perigrin** [perigrin/pvm#283]
## Problem

PVM module installation fails with uninformative error messages when module tests fail, making it difficult for users to understand what went wrong and how to resolve the issue.

## Error Details

**Command:** `pvm module install Feature::Compat::Class Scalar::Util`
**Result:** Partial failure - 1/2 modules installed successfully
**Failed Module:** Feature::Compat::Class v0.07
**Error Code:** SYS-PVI-4301 / SYS-PVI-4202

**Error Output:**
```
2025-08-10T12:35:34-04:00 [WARNING] [pvm] Tests failed for Feature::Compat::Class: exit status 255
...
Failed Installations
• ✗ Feature::Compat::Class: SYS-PVI-4301: Failed to build and install module Feature::Compat::Class (System Error)
  Cause: SYS-PVI-4202: Module tests failed (System Error)
  Location: /Users/perigrin/.cache/pvm/build/modules/Feature::Compat::Class-20250810-123532/Feature-Compat-Class-0.07
  Cause: exit status 255
```

**Important Context:** Feature::Compat::Class is specifically designed to work on older Perl versions (like 5.26.0) to provide experimental `class` syntax backport. The test failure is likely due to environment issues, build problems, or missing dependencies - not Perl version incompatibility.

### 1. **Insufficient Error Information**
- Generic "exit status 255" doesn't explain the actual test failure
- No test output captured or displayed to user
- No indication of which specific tests failed
- No guidance on whether failure is environment-specific or fundamental

### 2. **Missing Test Output**
- Test failures are logged as WARNING but details aren't shown
- Users can't determine if failures are critical or can be ignored
- No way to see actual test error messages or failures

### 3. **Limited Recovery Options**
- No option to skip tests and install anyway (like `cpanm --notest`)
- No option to force installation despite test failures
- No suggestion of alternative approaches or workarounds

### 4. **Inconsistent Behavior**
- Some modules (Scalar::Util) install fine, others fail
- No clear indication of why some tests pass and others fail
- Partial installation success not well communicated

### Expected Behavior
```bash
pvm module install Feature::Compat::Class
ℹ Installing Feature::Compat::Class...
ℹ Building and testing...
✗ Test failure in t/01basic.t: 
  - Test failed: Can't locate XS.pm in @INC
  - Likely cause: Missing build dependencies or XS compilation issue
  
⚠ Module tests failed. Options:
  1. Install anyway: pvm module install --force Feature::Compat::Class
  2. Skip tests: pvm module install --notest Feature::Compat::Class  
  3. Check dependencies: pvm module info Feature::Compat::Class
  4. View full test output: pvm module install --verbose Feature::Compat::Class
```

### Actual Behavior
```bash
✗ Feature::Compat::Class: SYS-PVI-4301: Failed to build and install module
  Cause: exit status 255
```

### 1. **Enhanced Error Reporting**

```go
// In internal/pm/modules/installer.go
type InstallationResult struct {
    Module          string
    Version         string
    Success         bool
    TestResults     *TestResults
    BuildOutput     string
    ErrorDetails    *DetailedError
}

type TestResults struct {
    Total           int
    Passed          int
    Failed          int
    Skipped         int
    FailedTests     []FailedTest
    Output          string
    Summary         string
}

type FailedTest struct {
    File            string
    TestName        string
    Error           string
    Line            int
}

type DetailedError struct {
    Code            string
    Message         string
    Cause           string
    RecoveryOptions []RecoveryOption
    Context         map[string]string
}
```

### 2. **Test Output Parsing**

```go
func (i *Installer) parseTestOutput(output string) *TestResults {
    results := &TestResults{}
    
    // Parse TAP (Test Anything Protocol) output
    lines := strings.Split(output, "\n")
    for _, line := range lines {
        if strings.HasPrefix(line, "not ok") {
            // Parse failed test details
            test := parseFailedTest(line)
            results.FailedTests = append(results.FailedTests, test)
            results.Failed++
        } else if strings.HasPrefix(line, "ok") {
            results.Passed++
        }
        // ... other TAP parsing
    }
    
    results.Total = results.Passed + results.Failed + results.Skipped
    return results
}
```

### 3. **Installation Options**

```go
type InstallOptions struct {
    SkipTests       bool    // --notest flag
    Force           bool    // --force flag (install despite test failures)
    Verbose         bool    // --verbose flag (show full test output)
    TestTimeout     time.Duration
    ShowTestOutput  bool    // Show real-time test output
}

func (i *Installer) InstallWithOptions(module string, opts InstallOptions) *InstallationResult {
    // ... build module
    
    if \!opts.SkipTests {
        testResult := i.runTests(buildDir, opts)
        if \!testResult.Success && \!opts.Force {
            return &InstallationResult{
                Success: false,
                TestResults: testResult,
                ErrorDetails: i.createDetailedError(testResult),
            }
        }
    }
    
    // Continue with installation...
}
```

### 4. **Recovery Suggestions**

```go
func (i *Installer) createDetailedError(testResults *TestResults) *DetailedError {
    error := &DetailedError{
        Code:    "SYS-PM-TEST-FAILED",
        Message: fmt.Sprintf("Module tests failed (%d/%d tests passed)", 
                testResults.Passed, testResults.Total),
        Cause:   i.analyzeFailureCause(testResults),
    }
    
    // Add recovery options based on failure analysis
    error.RecoveryOptions = []RecoveryOption{
        {
            Command:     fmt.Sprintf("pvm module install --notest %s", module),
            Description: "Skip tests and install anyway",
            Risk:        "Low - tests may fail due to environment issues",
        },
        {
            Command:     fmt.Sprintf("pvm module install --verbose %s", module),
            Description: "Show detailed test output for debugging",
            Risk:        "None - diagnostic information only",
        },
    }
    
    return error
}
```

### Phase 1: Enhanced Error Reporting
- Capture and parse test output during module installation
- Provide detailed error messages with specific test failure information
- Show recovery options and suggestions

### Phase 2: Installation Options
- Add `--notest` flag to skip module tests
- Add `--force` flag to install despite test failures
- Add `--verbose` flag to show detailed test output

### Phase 3: Test Output Analysis
- Parse TAP (Test Anything Protocol) output
- Identify common failure patterns (missing build tools, XS compilation issues, missing dependencies)
- Provide intelligent suggestions based on failure analysis

### Phase 4: User Experience Improvements
- Real-time test progress reporting
- Better formatting of installation summaries
- Integration with `pvm module info` for dependency checking

## CLI Flag Additions

```bash
# Skip tests (like cpanm --notest)
pvm module install --notest Feature::Compat::Class

# Force installation despite test failures
pvm module install --force Feature::Compat::Class

# Show detailed test output
pvm module install --verbose Feature::Compat::Class

# Show test details for failures only
pvm module install --test-details Feature::Compat::Class

# Set test timeout
pvm module install --test-timeout 300s Feature::Compat::Class
```

## Error Code Standardization

Current codes need updating:
- `SYS-PVI-4301` → `SYS-PM-4301` (reflects PVI→PM rename)
- `SYS-PVI-4202` → `SYS-PM-TEST-FAILED`

More specific error codes:
- `SYS-PM-TEST-TIMEOUT` - Tests timed out
- `SYS-PM-TEST-MISSING-DEPS` - Missing test dependencies
- `SYS-PM-TEST-BUILD-FAILED` - Build/compilation issue
- `SYS-PM-TEST-XS-FAILED` - XS compilation failure
- `SYS-PM-TEST-PLATFORM` - Platform-specific test failure

### Before (Current)
```
✗ Feature::Compat::Class: SYS-PVI-4301: Failed to build and install module
  Cause: exit status 255
```

### After (Proposed)
```
✗ Feature::Compat::Class v0.07: Module tests failed (3/24 tests failed)

Failed Tests:
  • t/01basic.t line 15: Can't locate XS.pm in @INC
  • t/02compile.t: Compilation failed during test
  • t/03methods.t line 8: Undefined symbol in XS module

Likely Cause: XS compilation or build dependency issue

Recovery Options:
  1. pvm module install --notest Feature::Compat::Class  # Skip tests (low risk)
  2. pvm module install --verbose Feature::Compat::Class  # Show full output
  3. Check build dependencies: pvm module info Feature::Compat::Class

For Feature::Compat::Class: This module should work on Perl 5.26.0
Test failures are likely due to build/environment issues, not compatibility.
```

## Implementation Tasks

- [ ] Update module installer to capture and parse test output
- [ ] Implement TAP (Test Anything Protocol) parser for test results
- [ ] Add `--notest`, `--force`, `--verbose` flags to module install command
- [ ] Create detailed error reporting with recovery suggestions
- [ ] Update error codes from PVI to PM naming
- [ ] Add test output analysis and common failure pattern detection
- [ ] Improve installation summary formatting and information
- [ ] Add integration with `pvm module info` for dependency checking
- [ ] Update documentation with new installation options
- [ ] Add tests for various module installation failure scenarios

## Testing Strategy

**Test Cases:**
- [ ] Module with failing tests (like Feature::Compat::Class)
- [ ] Module with missing build dependencies
- [ ] Module with XS compilation issues
- [ ] Module with platform-specific test failures
- [ ] Module with timeout issues
- [ ] Successful installation with `--notest` flag
- [ ] Successful installation with `--force` flag

## Related Issues

This improvement relates to:
- Module installation workflow enhancements
- Error reporting standardization
- User experience improvements
- PVI→PM naming cleanup (#263)

## Benefits

- **Better Debugging**: Users can understand why installations fail
- **Flexible Installation**: Options to handle test failures appropriately  
- **Improved UX**: Clear error messages with actionable recovery options
- **Reduced Confusion**: Avoid incorrect assumptions about module compatibility
- **Reduced Support**: Users can resolve issues without external help

## Acceptance Criteria

- [ ] Test failures show specific failed tests and error messages
- [ ] `--notest` flag skips module tests during installation
- [ ] `--force` flag installs modules despite test failures
- [ ] Error messages include recovery options and suggestions
- [ ] Installation summaries show detailed success/failure information
- [ ] Error codes updated from PVI to PM naming convention
- [ ] Documentation covers all new installation options
- [ ] Integration tests cover various failure scenarios

---

**Priority:** Medium (user experience and debugging improvement)
**Component:** PM (Package Manager), Module Installation  
**Effort:** Medium - requires test output parsing and UI improvements
**Impact:** High - significantly improves user experience with failed installations

**Comment by perigrin** [comment]
This issue has been resolved by PR #286 which implemented comprehensive error reporting improvements including:

✅ Enhanced module installation error reporting with detailed test failure information
✅ TAP parser for parsing test output () 
✅  flag implementation ()
✅ User-friendly error messages with recovery options
✅ Removal of cryptic error codes

All the requirements from this issue have been addressed. The functionality is now available in the merged code.
